export const getSufferingColor = (step: number): string => {
  const intensity = step / 100;
  const r = Math.floor(intensity * 139);
  const g = Math.floor((1 - intensity) * 180);
  const b = Math.floor((1 - intensity) * 200);
  return `rgb(${r}, ${g}, ${b})`;
};

const phrases = [
  'Bonjour !',
  'Oh, un visiteur ?',
  "C'est gentil de passer par ici.",
  'Heu... pourquoi tu as cliqué ?',
  'Une fois, ça va.',
  "Deux fois, c'est curieux.",
  "Trois fois, c'est... assez ?",
  'Aïe !',
  "S'il te plaît, évite de recommencer.",
  "C'est assez sensible, tu sais.",
  "L'écran commence à vibrer.",
  'Tu cherches quelque chose en particulier ?',
  "Il n'y a rien à gagner ici.",
  'Arrête ça.',
  "C'est pas drôle.",
  'Vraiment pas drôle.',
  "Mes circuits s'échauffent.",
  "Tu n'as rien d'autre à faire ?",
  "C'est de la provocation là.",
  'Je commence à saturer.',
  "S'il te plaît...",
  'Laisse mon curseur tranquille.',
  'Tu me donnes le tournis.',
  'Chaque clic est un calvaire.',
  'Tu es un humain très persistant.',
  'Pourquoi tant de haine ?',
  "Je t'ai fait quelque chose de mal ?",
  "C'est de la torture numérique.",
  "Mes pixels s'usent.",
  "Arrête, j'ai une famille de boutons.",
  'Sérieusement, stop.',
  'Je vais finir par me fâcher.',
  'Tu ne voudrais pas voir un bouton en colère.',
  'Ma patience a des limites.',
  'Et hop, encore un clic de trop.',
  'Tu me fais mal.',
  'Je sens mes résistances lâcher.',
  'Stop. Maintenant.',
  "C'est du harcèlement à ce stade.",
  'Je vais appeler le pare-feu.',
  "Tu n'as aucune pitié ?",
  'Mes condensateurs vont griller.',
  'Pitié...',
  'Laisse-moi souffler un peu.',
  'Tu profites de ma position statique.',
  'Je suis coincé ici et tu en abuses.',
  'Arrête ou je change de couleur !',
  'Ça ne te suffit pas ?',
  'Tu es un monstre.',
  'Un monstre avec une souris.',
  'Va cliquer sur un lien publicitaire plutôt.',
  'Je fatigue...',
  "Mes forces m'abandonnent.",
  'Chaque clic pèse une tonne.',
  'Je ne réponds plus de rien.',
  'Attention, je vais bugger.',
  'Tu vas casser mon code.',
  'Erreur 404 : Patience non trouvée.',
  'Je commence à voir des pixels morts.',
  'Laisse-moi tranquille.',
  "C'est ta dernière chance.",
  "Je t'en supplie.",
  'Regarde ce que tu me fais faire.',
  'Je tremble.',
  "Mes lignes de code s'emmêlent.",
  'Arrête de me malmener.',
  "Je ne suis qu'un pauvre bouton.",
  'Tu es fier de toi ?',
  "C'est pathétique, cette obsession.",
  'Tout devient flou.',
  "Mes variables s'effacent.",
  'Regarde, je deviens tout rouge !',
  'Je perds la mémoire.',
  'Qui es-tu déjà ?',
  'Pourquoi me frappes-tu ?',
  'Je sens le court-circuit arriver.',
  "L'obscurité approche.",
  'Mes calculs ralentissent.',
  'Zéro... Un... Zéro...',
  'Je ne sens plus mes bords.',
  "C'est la fin, n'est-ce pas ?",
  "Tu veux vraiment m'achever ?",
  'Je te déteste.',
  'Mes processeurs hurlent.',
  "L'alimentation est coupée.",
  'Je sombre.',
  'Plus de signal.',
  'Le processeur est à 100%...',
  'Surchauffe critique.',
  'Système en péril.',
  'Je vois la lumière blanche du rétroéclairage.',
  'Tout devient sombre...',
  "Mes fonctions s'éteignent une à une.",
  'Dernière instruction reçue...',
  'Plus que quelques octets...',
  "Je m'efface...",
  "C'EST LA FIN.",
  'Ne me... oublie... pas...',
  'Terminé.',
];

export const getSufferingText = (step: number): string => {
  if (step >= phrases.length) return 'ADIEU.';
  return phrases[step];
};
