services:
  frontend:
    build: .
    container_name: owl-nest-web
    restart: unless-stopped
    networks:
      - proxy-net

    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owl-nest.rule=Host(`owl-nest.ch`) || Host(`www.owl-nest.ch`)"
      - "traefik.http.routers.owl-nest.entrypoints=web"
      - "traefik.http.services.owl-nest.loadbalancer.server.port=8080"

networks:
  proxy-net:
    external: true
