server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gestion du routage React (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimisation du cache pour les assets statiques (JS, CSS, Images)
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Page d'erreur personnalisée
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
