name: Deploy to Raspberry Pi

on:
  pull_request:
    types: [labeled] # Se déclenche quand on ajoute un label à une PR

jobs:
  deploy:
    if: github.event.label.name == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/owl-nest
            git pull origin main
            docker compose build
            docker compose up -d
